# GERADO por `theme` — edite theme/templates/kitty-theme.conf.tmpl
foreground            #adb8b8
background            #00141a
selection_foreground  #adb8b8
selection_background  #0a3d4a

cursor                #adb8b8
cursor_text_color     #00141a

url_color             #278bd3

active_border_color   #278bd3
inactive_border_color #586e74
bell_border_color     #dc312e

active_tab_foreground   #00141a
active_tab_background   #278bd3
inactive_tab_foreground #818a8a
inactive_tab_background #073541

# preto / cinza
color0  #073541
color8  #586e74
# vermelho
color1  #dc312e
color9  #dc312e
# verde
color2  #859900
color10 #859900
# amarelo (no Carbonfox este slot e teal)
color3  #b28600
color11 #b28600
# azul
color4  #278bd3
color12 #278bd3
# magenta
color5  #d33682
color13 #d33682
# ciano
color6  #2aa298
color14 #2aa298
# branco
color7  #818a8a
color15 #adb8b8
