#? Config file for btop
color_theme = "/home/erick/.config/btop/themes/current.theme"
theme_background = True
truecolor = True
vim_keys = False
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
show_gpu_info = "On"
