# GERADO por `theme` — edite theme/templates/yazi-theme.toml.tmpl

[mgr]
cwd             = { fg = "#278bd3" }
hovered         = { fg = "#00141a", bg = "#278bd3" }
preview_hovered = { underline = true }

find_keyword  = { fg = "#b28600", bold = true }
find_position = { fg = "#d33682", bg = "reset", bold = true }

marker_copied   = { fg = "#859900",   bg = "#859900" }
marker_cut      = { fg = "#dc312e",     bg = "#dc312e" }
marker_marked   = { fg = "#2aa298",    bg = "#2aa298" }
marker_selected = { fg = "#d33682", bg = "#d33682" }

tab_active   = { fg = "#00141a", bg = "#278bd3" }
tab_inactive = { fg = "#818a8a", bg = "#073541" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#586e74" }

[mode]
normal_main = { fg = "#00141a", bg = "#278bd3",  bold = true }
normal_alt  = { fg = "#278bd3", bg = "#073541" }
select_main = { fg = "#00141a", bg = "#859900",   bold = true }
select_alt  = { fg = "#859900",  bg = "#073541" }
unset_main  = { fg = "#00141a", bg = "#d33682", bold = true }
unset_alt   = { fg = "#d33682", bg = "#073541" }

[status]
overall   = { fg = "#adb8b8" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[select]
border   = { fg = "#278bd3" }
active   = { fg = "#d33682" }
inactive = {}

[input]
border   = { fg = "#278bd3" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#278bd3" }
active   = { fg = "#d33682" }
inactive = {}

[confirm]
border  = { fg = "#278bd3" }
title   = { fg = "#278bd3" }
content = {}
list    = {}

[filetype]
rules = [
  { mime = "image/*", fg = "#2aa298" },
  { mime = "video/*", fg = "#d33682" },
  { mime = "audio/*", fg = "#d33682" },
  { mime = "application/zip",   fg = "#dc312e" },
  { mime = "application/gzip",  fg = "#dc312e" },
  { mime = "application/x-tar", fg = "#dc312e" },
  { mime = "application/pdf",   fg = "#dc312e" },
  { url = "*/", fg = "#278bd3" },
  { url = "*",  fg = "#adb8b8" },
]
