# GERADO por `theme` — edite theme/templates/btop.theme.tmpl
theme[main_bg]="#161616"
theme[main_fg]="#f2f4f8"
theme[title]="#f2f4f8"
theme[hi_fg]="#78a9ff"
theme[selected_bg]="#282828"
theme[selected_fg]="#78a9ff"
theme[inactive_fg]="#6f6f6f"
theme[graph_text]="#b5b7ba"
theme[meter_bg]="#484848"
theme[proc_misc]="#33b1ff"

theme[cpu_box]="#484848"
theme[mem_box]="#484848"
theme[net_box]="#484848"
theme[proc_box]="#484848"
theme[div_line]="#484848"

theme[temp_start]="#25be6a"
theme[temp_mid]="#be95ff"
theme[temp_end]="#ee5396"

theme[cpu_start]="#33b1ff"
theme[cpu_mid]="#78a9ff"
theme[cpu_end]="#be95ff"

theme[free_start]="#25be6a"
theme[free_mid]=""
theme[free_end]="#08bdba"

theme[cached_start]="#33b1ff"
theme[cached_mid]=""
theme[cached_end]="#78a9ff"

theme[available_start]="#08bdba"
theme[available_mid]=""
theme[available_end]="#25be6a"

theme[used_start]="#be95ff"
theme[used_mid]=""
theme[used_end]="#ee5396"

theme[download_start]="#25be6a"
theme[download_mid]=""
theme[download_end]="#33b1ff"

theme[upload_start]="#be95ff"
theme[upload_mid]=""
theme[upload_end]="#ee5396"

theme[process_start]="#33b1ff"
theme[process_mid]="#78a9ff"
theme[process_end]="#be95ff"
