# GERADO por `theme` — edite theme/templates/btop.theme.tmpl
theme[main_bg]="#00141a"
theme[main_fg]="#adb8b8"
theme[title]="#adb8b8"
theme[hi_fg]="#278bd3"
theme[selected_bg]="#073541"
theme[selected_fg]="#278bd3"
theme[inactive_fg]="#647a82"
theme[graph_text]="#818a8a"
theme[meter_bg]="#586e74"
theme[proc_misc]="#2aa298"

theme[cpu_box]="#586e74"
theme[mem_box]="#586e74"
theme[net_box]="#586e74"
theme[proc_box]="#586e74"
theme[div_line]="#586e74"

theme[temp_start]="#859900"
theme[temp_mid]="#d33682"
theme[temp_end]="#dc312e"

theme[cpu_start]="#2aa298"
theme[cpu_mid]="#278bd3"
theme[cpu_end]="#d33682"

theme[free_start]="#859900"
theme[free_mid]=""
theme[free_end]="#b28600"

theme[cached_start]="#2aa298"
theme[cached_mid]=""
theme[cached_end]="#278bd3"

theme[available_start]="#b28600"
theme[available_mid]=""
theme[available_end]="#859900"

theme[used_start]="#d33682"
theme[used_mid]=""
theme[used_end]="#dc312e"

theme[download_start]="#859900"
theme[download_mid]=""
theme[download_end]="#2aa298"

theme[upload_start]="#d33682"
theme[upload_mid]=""
theme[upload_end]="#dc312e"

theme[process_start]="#2aa298"
theme[process_mid]="#278bd3"
theme[process_end]="#d33682"
